services:
  dynamodb:
    image: amazon/dynamodb-local:2.6.1
    command: "-jar DynamoDBLocal.jar -sharedDb"
    ports:
      - "8000:8000"

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin:5.1.3
    environment:
      DYNAMO_ENDPOINT: http://dynamodb:8000
    ports:
      - "8001:8001"
    depends_on:
      dynamodb:
        condition: service_started
